run:
  timeout: 3m

linters-settings:
  cyclop:
    max-complexity: 30
    package-average: 10.0

  errcheck:
    check-type-assertions: true

  exhaustive:
    check:
      - switch
      - map

  funlen:
    lines: 150
    statements: 80

  gocognit:
    min-complexity: 50

  gosec:
    excludes:
      - G204

  govet:
    enable-all: true
    disable-all: false
    disable:
      - fieldalignment

  nakedret:
    max-func-lines: 10

  lll:
    line-length: 180

  staticcheck:
    checks: ["all", "-SA1019"]

linters:
  enable:
    - cyclop
    - errname
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - godot
    - goimports
    - gosec
    - lll
    - loggercheck
    - makezero
    - nakedret
    - nilerr
    - nilnil
    - nolintlint
    - nonamedreturns
    - predeclared
    - reassign
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace
issues:
  # Replacing deprecated run.skip-files
  exclude-files:
    - ".*_test.go$"

  # Replacing deprecated run.skip-dirs
  exclude-dirs:
    - "test"        # Skip whole test directories if you have dedicated test folders
    - "mocks"       # Skip mock directories
    - "testdata"    # Skip testdata directories
    - "tests"